### ISSUE TITLE
"这是 Frost 的个人网站" remained in widget.swig

### ISSUE THREAD

**Issue by cettoana** [frostfan/hexo-theme-polarbear#1]
"这是 Frost 的个人网站" remained in widget.swig.

I think it should be {{ config.description }} or something?

Thanks :)

**Comment by frostfan** [comment]
Thanks for your advice and star. The new version 1.1 fixed this problem and added widget functions. 😄

**Comment by cettoana** [comment]
You're welcome :)
This is really a nice theme, I love the design.
