### ISSUE TITLE
readmore设置问题

### ISSUE THREAD

**Issue by lanemo** [frostfan/hexo-theme-polarbear#12]
您好~这个主题感觉非常干净，很喜欢。

有一个关于文章首页的截断显示的问题。我根据基础主题evan的配置，加入`<!-- more -->`的代码。可以成功在首页显示截断文字，但是没有出现evan教程里的readmore按钮。想请问一下是什么问题…

另外，请问博客的主标题main_title可以修改颜色吗？

非常感谢解答~

**Comment by frostfan** [comment]
这个主题去掉了 readmore 文字，main_title 颜色可以改scss实现
