### ISSUE TITLE
请问一下如何向DEMO那样在主页的目录上显示文章预览？

### ISSUE THREAD

**Issue by mingyec** [frostfan/hexo-theme-polarbear#13]
如题所示，我按照作者的配置后无法达到和DEMO一样的效果

**Comment by frostfan** [comment]
文章中加：，看看可以吗

**Comment by mingyec** [comment]
额，抱歉没看明白你的意思，是在文章的哪里加？

**Comment by mingyec** [comment]
要不dalao给个文章示例？

**Comment by uQingTao** [comment]
@mingyec 这样可以的：[添加首页文章阅读全文](https://github.com/ahonn/hexo-theme-even/wiki/%E6%B7%BB%E5%8A%A0%E9%A6%96%E9%A1%B5%E6%96%87%E7%AB%A0%E9%98%85%E8%AF%BB%E5%85%A8%E6%96%87)

**Comment by mingyec** [comment]
@Pskoty 感谢:）
