### ISSUE TITLE
请问下如何添加页内文章目录

### ISSUE THREAD

**Issue by YoungLightMing** [frostfan/hexo-theme-polarbear#16]
引用了你的主题，并做了些许更改，但添加 Toc 遇到了问题。

我已经添加了 `toc.swig`  文件并且在文章内插入，对于 `config.swig` 文件，该如何使用，谢谢！

**Comment by YoungLightMing** [comment]
已解决。

**Comment by w2i4da** [comment]
> 
> 
> 已解决。
求解决方式，我也想要在里面添加文章目录，谢谢

**Comment by ghost** [comment]
@YoungLightMing 您好，请问您是如何解决的，可以说一下么？
