### ISSUE TITLE
提问：按照Installation安装后主页显示错误

### ISSUE THREAD

**Issue by zhollow** [frostfan/hexo-theme-polarbear#21]
我按照Installation安装的，`generate`然后`server`，打开`localhost:4000`页面里是这个样子：

```
{% extends "_layout.swig" %} {% import '_macro/post.swig' as post_template %} {% block title %} {{ config.title }} - {{ config.description }}{% endblock %} {% block content %}
{% for post in page.posts %} {{ post_template.render(post) }} {% endfor %} {% include "_partial/pagination.swig" %}
{% include "_partial/widget.swig" %} {% endblock %}
```

感觉就是模板没有渲染一样，请问可能是哪个地方出错了呢？

**Comment by zhollow** [comment]
问题已解决，是`hexo-renderer-swig`没有装（竟然没有任何报错！），在[Even](https://github.com/ahonn/hexo-theme-even)主题下发现的这个依赖。

希望能在Installation中写明，不然向我这样不熟悉的人真不知道怎么搞。

**Comment by BoWang816** [comment]
> 问题已解决，是`hexo-renderer-swig`没有装（竟然没有任何报错！），在[Even](https://github.com/ahonn/hexo-theme-even)主题下发现的这个依赖。
> 
> 希望能在Installation中写明，不然向我这样不熟悉的人真不知道怎么搞。

我都准备不用了，然后看见了你这条！

**Comment by frostfan** [comment]
已在 Installation 中写明：需要安装 hexo-renderer-swig
